### ISSUE TITLE
Search: Wildcard

### ISSUE THREAD

**Issue by leun4m** [leun4m/symbsearch#38]
To have a search with wildcards would be nice - I would suggest a *

**Comment by oliver-krebs** [comment]
The search in the mono-gtk branch is already improved, so that the searchtext is splitted at whitespace. Then a contain check for all these substrings is done. The result is a behavior like a default wildcard for start and end of all given terms.
https://github.com/leun4m/symbsearch/commit/7a355d1f798f1a2402a50a079571246d478be6ee

**Comment by leun4m** [comment]
Okay, think we can close it then.
